%% Automated Programmatic Builder for Quarter-Car MR Damper Simulink Model
% Author: W. M. Baig
% Creates: Quarter_Car_MRD.slx
%
% When executed in MATLAB, this script programmatically generates a clean,
% modular, and hierarchically organized Simulink model with:
%   1. Road_Excitation Subsystem (Bump, Chirp, ISO Random, Step)
%   2. 2-DOF Quarter-Car Dynamics Subsystem (m_s, m_u, k_s, k_t)
%   3. Spencer Modified Bouc-Wen MR Damper Subsystem (eta coil, alpha, c0, c1, y, z)
%   4. Semi-Active Controller Subsystem (Passive 0V/2V, Skyhook, Continuous, Hybrid)
%   5. Performance Scopes & Outport Loggers

clear; clc;

model_name = 'Quarter_Car_MRD';

% Close model if already open
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

% Create new model system
new_system(model_name);
open_system(model_name);

fprintf('Building organized Simulink model: %s.slx...\n', model_name);

%% Configure Solver Settings
set_param(model_name, 'SolverType', 'Fixed-step');
set_param(model_name, 'Solver', 'ode4');             % 4th-Order Runge-Kutta
set_param(model_name, 'FixedStep', '5e-5');          % 50 microseconds (satisfies Bouc-Wen stiffness)
set_param(model_name, 'StopTime', 'SimTime');
set_param(model_name, 'SaveTime', 'on');
set_param(model_name, 'TimeSaveName', 'tout');
set_param(model_name, 'SaveOutput', 'on');
set_param(model_name, 'OutputSaveName', 'yout');
set_param(model_name, 'SaveFormat', 'Dataset');

%% 1. Road Excitation Subsystem
road_sub = [model_name '/Road_Excitation'];
add_block('simulink/Ports & Subsystems/Subsystem', road_sub, 'Position', [60, 200, 200, 310]);
% Clear default in/out in subsystem
delete_line(road_sub, 'In1/1', 'Out1/1');
delete_block([road_sub '/In1']);

% Road switch logic
add_block('simulink/Sources/Constant', [road_sub '/RoadType'], 'Value', 'RoadType', 'Position', [30, 30, 70, 60]);
add_block('simulink/Signal Routing/Multiport Switch', [road_sub '/Road_Switch'], 'DataPortOrder', 'Zero-based contiguous', 'Inputs', '4', 'Position', [340, 70, 380, 250]);

% Option 1: Haversine bump
add_block('simulink/User-Defined Functions/MATLAB Function', [road_sub '/Haversine_Bump'], 'Position', [120, 80, 260, 130]);
bump_code = sprintf([...
    'function [zr, zr_dot] = Haversine_Bump(t, H, L, v, t_start)\n', ...
    't_end = t_start + L / v;\n', ...
    'if t >= t_start && t <= t_end\n', ...
    '    tau = (t - t_start) / (L / v);\n', ...
    '    zr = 0.5 * H * (1 - cos(2 * pi * tau));\n', ...
    '    zr_dot = 0.5 * H * (2 * pi / (L / v)) * sin(2 * pi * tau);\n', ...
    'else\n', ...
    '    zr = 0.0;\n', ...
    '    zr_dot = 0.0;\n', ...
    'end\n']);
set_param([road_sub '/Haversine_Bump'], 'Script', bump_code);

% Option 2: Chirp sweep
add_block('simulink/Sources/Chirp Signal', [road_sub '/Chirp'], 'f1', 'Chirp_f0', 'f2', 'Chirp_f1', 'T', 'Chirp_T', 'Position', [140, 150, 180, 180]);
add_block('simulink/Math Operations/Gain', [road_sub '/Chirp_Gain'], 'Gain', 'Chirp_Amp', 'Position', [220, 150, 260, 180]);
add_block('simulink/Continuous/Derivative', [road_sub '/Chirp_Deriv'], 'Position', [280, 165, 310, 195]);

% Option 3: Step
add_block('simulink/Sources/Step', [road_sub '/Step_Input'], 'Time', 'Step_Time', 'After', 'Step_Height', 'Position', [140, 210, 180, 240]);
add_block('simulink/Continuous/Derivative', [road_sub '/Step_Deriv'], 'Position', [220, 225, 250, 255]);

% Clock & Inputs to Haversine
add_block('simulink/Sources/Clock', [road_sub '/Clock'], 'Position', [30, 85, 60, 105]);
add_block('simulink/Sources/Constant', [road_sub '/H_param'], 'Value', 'Bump_Height', 'Position', [30, 115, 60, 135]);
add_block('simulink/Sources/Constant', [road_sub '/L_param'], 'Value', 'Bump_Length', 'Position', [30, 145, 60, 165]);
add_block('simulink/Sources/Constant', [road_sub '/v_param'], 'Value', 'Car_Speed_mps', 'Position', [30, 175, 60, 195]);
add_block('simulink/Sources/Constant', [road_sub '/t0_param'], 'Value', 'Bump_StartTime', 'Position', [30, 205, 60, 225]);

add_block('simulink/Ports & Subsystems/Outport', [road_sub '/z_r'], 'Position', [450, 130, 480, 150]);
add_block('simulink/Ports & Subsystems/Outport', [road_sub '/z_r_dot'], 'Position', [450, 190, 480, 210]);

%% 2. Semi-Active Controller Subsystem
ctrl_sub = [model_name '/Semi_Active_Controller'];
add_block('simulink/Ports & Subsystems/Subsystem', ctrl_sub, 'Position', [280, 50, 420, 160]);
delete_line(ctrl_sub, 'In1/1', 'Out1/1');

add_block('simulink/Ports & Subsystems/Inport', [ctrl_sub '/z_s_dot'], 'Position', [30, 50, 60, 70]);
add_block('simulink/Ports & Subsystems/Inport', [ctrl_sub '/z_u_dot'], 'Position', [30, 100, 60, 120]);
add_block('simulink/Ports & Subsystems/Inport', [ctrl_sub '/susp_vel'], 'Position', [30, 150, 60, 170]);

% MATLAB Function for controller arbitration
add_block('simulink/User-Defined Functions/MATLAB Function', [ctrl_sub '/Control_Logic'], 'Position', [140, 60, 310, 160]);
ctrl_code = sprintf([...
    'function V_cmd = Control_Logic(z_s_dot, z_u_dot, susp_vel, mode, V_min, V_max, C_sky, F_ref, alpha_hyb)\n', ...
    'switch mode\n', ...
    '    case 0 %% Passive Soft\n', ...
    '        V_cmd = V_min;\n', ...
    '    case 1 %% Passive Hard\n', ...
    '        V_cmd = V_max;\n', ...
    '    case 2 %% Skyhook 2-State\n', ...
    '        if z_s_dot * susp_vel >= 0\n', ...
    '            V_cmd = V_max;\n', ...
    '        else\n', ...
    '            V_cmd = V_min;\n', ...
    '        end\n', ...
    '    case 3 %% Continuous Skyhook\n', ...
    '        if z_s_dot * susp_vel >= 0\n', ...
    '            f_des = C_sky * abs(z_s_dot);\n', ...
    '            V_cmd = V_min + (f_des / F_ref) * (V_max - V_min);\n', ...
    '            V_cmd = min(V_max, max(V_min, V_cmd));\n', ...
    '        else\n', ...
    '            V_cmd = V_min;\n', ...
    '        end\n', ...
    '    case 4 %% Hybrid Skyhook-Groundhook\n', ...
    '        sigma = alpha_hyb * z_s_dot - (1 - alpha_hyb) * z_u_dot;\n', ...
    '        if sigma * susp_vel >= 0\n', ...
    '            V_cmd = V_max;\n', ...
    '        else\n', ...
    '            V_cmd = V_min;\n', ...
    '        end\n', ...
    '    otherwise\n', ...
    '        V_cmd = V_min;\n', ...
    'end\n']);
set_param([ctrl_sub '/Control_Logic'], 'Script', ctrl_code);

% Add parameters to controller subsystem
add_block('simulink/Sources/Constant', [ctrl_sub '/ControlMode'], 'Value', 'ControlMode', 'Position', [30, 200, 60, 220]);
add_block('simulink/Sources/Constant', [ctrl_sub '/V_min_blk'], 'Value', 'V_min', 'Position', [30, 240, 60, 260]);
add_block('simulink/Sources/Constant', [ctrl_sub '/V_max_blk'], 'Value', 'V_max', 'Position', [30, 280, 60, 300]);
add_block('simulink/Sources/Constant', [ctrl_sub '/C_sky_blk'], 'Value', 'C_sky', 'Position', [30, 320, 60, 340]);
add_block('simulink/Sources/Constant', [ctrl_sub '/F_ref_blk'], 'Value', 'F_ref_sky', 'Position', [30, 360, 60, 380]);
add_block('simulink/Sources/Constant', [ctrl_sub '/alpha_hyb_blk'], 'Value', 'alpha_hybrid', 'Position', [30, 400, 60, 420]);

add_block('simulink/Ports & Subsystems/Outport', [ctrl_sub '/V_cmd'], 'Position', [360, 100, 390, 120]);

%% 3. MR Damper Subsystem (Spencer Modified Bouc-Wen)
mrd_sub = [model_name '/MR_Damper_Bouc_Wen'];
add_block('simulink/Ports & Subsystems/Subsystem', mrd_sub, 'Position', [500, 80, 660, 210]);
delete_line(mrd_sub, 'In1/1', 'Out1/1');

add_block('simulink/Ports & Subsystems/Inport', [mrd_sub '/V_cmd'], 'Position', [30, 50, 60, 70]);
add_block('simulink/Ports & Subsystems/Inport', [mrd_sub '/susp_defl'], 'Position', [30, 110, 60, 130]);
add_block('simulink/Ports & Subsystems/Inport', [mrd_sub '/susp_vel'], 'Position', [30, 170, 60, 190]);

add_block('simulink/User-Defined Functions/MATLAB Function', [mrd_sub '/Spencer_MBW_Dynamics'], 'Position', [140, 60, 340, 180]);
mbw_code = sprintf([...
    'function [F_MR, u_eff] = Spencer_MBW_Dynamics(V_cmd, x, x_dot, ' ...
    'c0_a, c0_b, k0, c1_a, c1_b, k1, x0, alpha_a, alpha_b, gamma, beta, A, n, eta, V_min, V_max, c_s_lin, mode, dt)\n', ...
    'persistent y_int z_int u_int\n', ...
    'if isempty(y_int)\n', ...
    '    y_int = 0.0;\n', ...
    '    z_int = 0.0;\n', ...
    '    u_int = 0.0;\n', ...
    'end\n', ...
    'if mode == -1\n', ...
    '    %% Basic Linear Passive Damper\n', ...
    '    F_MR = c_s_lin * x_dot;\n', ...
    '    u_eff = 0.0;\n', ...
    '    return;\n', ...
    'end\n', ...
    'v_clamped = min(V_max, max(V_min, V_cmd));\n', ...
    'du = -eta * (u_int - v_clamped);\n', ...
    'u_int = u_int + du * dt;\n', ...
    'u_int = min(V_max, max(V_min, u_int));\n', ...
    'alpha = alpha_a + alpha_b * u_int;\n', ...
    'c0 = c0_a + c0_b * u_int;\n', ...
    'c1 = c1_a + c1_b * u_int;\n', ...
    'dy = (alpha * z_int + c0 * x_dot + k0 * (x - y_int)) / (c0 + c1);\n', ...
    'y_int = y_int + dy * dt;\n', ...
    'vel_rel = x_dot - dy;\n', ...
    'abs_z = abs(z_int);\n', ...
    'z_n = abs_z^n;\n', ...
    'if abs_z > 1e-18\n', ...
    '    z_n_m1 = abs_z^(n - 1);\n', ...
    'else\n', ...
    '    z_n_m1 = 0.0;\n', ...
    'end\n', ...
    'dz = A * vel_rel - beta * vel_rel * z_n - gamma * abs(vel_rel) * z_n_m1 * z_int;\n', ...
    'z_int = z_int + dz * dt;\n', ...
    'z_int = min(0.015, max(-0.015, z_int));\n', ...
    'F_MR = c1 * dy + k1 * (x - x0);\n', ...
    'u_eff = u_int;\n']);
set_param([mrd_sub '/Spencer_MBW_Dynamics'], 'Script', mbw_code);

add_block('simulink/Sources/Constant', [mrd_sub '/c_s_lin_blk'], 'Value', 'c_s_linear', 'Position', [30, 230, 60, 250]);
add_block('simulink/Sources/Constant', [mrd_sub '/mode_blk'], 'Value', 'ControlMode', 'Position', [30, 270, 60, 290]);

add_block('simulink/Ports & Subsystems/Outport', [mrd_sub '/F_MR'], 'Position', [400, 80, 430, 100]);
add_block('simulink/Ports & Subsystems/Outport', [mrd_sub '/u_eff'], 'Position', [400, 140, 430, 160]);

%% 4. Quarter-Car Dynamics Subsystem
qc_sub = [model_name '/Quarter_Car_Dynamics'];
add_block('simulink/Ports & Subsystems/Subsystem', qc_sub, 'Position', [280, 220, 440, 380]);
delete_line(qc_sub, 'In1/1', 'Out1/1');

add_block('simulink/Ports & Subsystems/Inport', [qc_sub '/F_MR'], 'Position', [30, 50, 60, 70]);
add_block('simulink/Ports & Subsystems/Inport', [qc_sub '/z_r'], 'Position', [30, 110, 60, 130]);
add_block('simulink/Ports & Subsystems/Inport', [qc_sub '/z_r_dot'], 'Position', [30, 170, 60, 190]);

add_block('simulink/User-Defined Functions/MATLAB Function', [qc_sub '/Two_DOF_EOM'], 'Position', [140, 50, 320, 200]);
qc_code = sprintf([...
    'function [z_s, z_s_dot, z_s_ddot, z_u, z_u_dot, z_u_ddot, susp_defl, susp_vel, tire_defl, F_tire] = ' ...
    'Two_DOF_EOM(F_MR, z_r, z_r_dot, m_s, m_u, k_s, c_s_pass, k_t, c_t, dt)\n', ...
    'persistent zs zs_dot zu zu_dot\n', ...
    'if isempty(zs)\n', ...
    '    zs = 0.0; zs_dot = 0.0;\n', ...
    '    zu = 0.0; zu_dot = 0.0;\n', ...
    'end\n', ...
    'susp_defl = zs - zu;\n', ...
    'susp_vel  = zs_dot - zu_dot;\n', ...
    'tire_defl = zu - z_r;\n', ...
    'tire_vel  = zu_dot - z_r_dot;\n', ...
    'f_spring = k_s * susp_defl + c_s_pass * susp_vel;\n', ...
    'F_tire   = k_t * tire_defl + c_t * tire_vel;\n', ...
    'z_s_ddot = (-f_spring - F_MR) / m_s;\n', ...
    'z_u_ddot = (f_spring + F_MR - F_tire) / m_u;\n', ...
    'zs_dot = zs_dot + z_s_ddot * dt;\n', ...
    'zs     = zs + zs_dot * dt;\n', ...
    'zu_dot = zu_dot + z_u_ddot * dt;\n', ...
    'zu     = zu + zu_dot * dt;\n', ...
    'z_s = zs;\n', ...
    'z_s_dot = zs_dot;\n', ...
    'z_u = zu;\n', ...
    'z_u_dot = zu_dot;\n']);
set_param([qc_sub '/Two_DOF_EOM'], 'Script', qc_code);

add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/z_s'], 'Position', [380, 40, 410, 60]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/z_s_dot'], 'Position', [380, 80, 410, 100]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/z_s_ddot'], 'Position', [380, 120, 410, 140]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/z_u'], 'Position', [380, 160, 410, 180]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/z_u_dot'], 'Position', [380, 200, 410, 220]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/susp_defl'], 'Position', [380, 240, 410, 260]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/susp_vel'], 'Position', [380, 280, 410, 300]);
add_block('simulink/Ports & Subsystems/Outport', [qc_sub '/tire_defl'], 'Position', [380, 320, 410, 340]);

%% 5. Top-Level Scopes and Workspace Outports
add_block('simulink/Sinks/Scope', [model_name '/Scope_Ride_Comfort'], 'Position', [750, 40, 780, 80]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_Susp_Travel'], 'Position', [750, 120, 780, 160]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_Damper_Force'], 'Position', [750, 200, 780, 240]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_Tire_Deflection'], 'Position', [750, 280, 780, 320]);

% To Workspace blocks for post-processing
add_block('simulink/Sinks/To Workspace', [model_name '/ToWksp_zs'], 'VariableName', 'z_s_out', 'SaveFormat', 'Timeseries', 'Position', [750, 360, 810, 380]);
add_block('simulink/Sinks/To Workspace', [model_name '/ToWksp_acc'], 'VariableName', 'acc_out', 'SaveFormat', 'Timeseries', 'Position', [750, 400, 810, 420]);
add_block('simulink/Sinks/To Workspace', [model_name '/ToWksp_force'], 'VariableName', 'force_out', 'SaveFormat', 'Timeseries', 'Position', [750, 440, 810, 460]);

%% Wire Subsystems at Top Level
% Road -> Quarter Car
add_line(model_name, 'Road_Excitation/1', 'Quarter_Car_Dynamics/2', 'autorouting', 'on');
add_line(model_name, 'Road_Excitation/2', 'Quarter_Car_Dynamics/3', 'autorouting', 'on');

% Quarter Car -> Semi-Active Controller
add_line(model_name, 'Quarter_Car_Dynamics/2', 'Semi_Active_Controller/1', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/5', 'Semi_Active_Controller/2', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/7', 'Semi_Active_Controller/3', 'autorouting', 'on');

% Semi-Active Controller -> MR Damper
add_line(model_name, 'Semi_Active_Controller/1', 'MR_Damper_Bouc_Wen/1', 'autorouting', 'on');

% Quarter Car -> MR Damper kinematics
add_line(model_name, 'Quarter_Car_Dynamics/6', 'MR_Damper_Bouc_Wen/2', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/7', 'MR_Damper_Bouc_Wen/3', 'autorouting', 'on');

% MR Damper Force -> Quarter Car
add_line(model_name, 'MR_Damper_Bouc_Wen/1', 'Quarter_Car_Dynamics/1', 'autorouting', 'on');

% Signals -> Scopes & Workspaces
add_line(model_name, 'Quarter_Car_Dynamics/1', 'Scope_Ride_Comfort/1', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/6', 'Scope_Susp_Travel/1', 'autorouting', 'on');
add_line(model_name, 'MR_Damper_Bouc_Wen/1', 'Scope_Damper_Force/1', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/8', 'Scope_Tire_Deflection/1', 'autorouting', 'on');

add_line(model_name, 'Quarter_Car_Dynamics/1', 'ToWksp_zs/1', 'autorouting', 'on');
add_line(model_name, 'Quarter_Car_Dynamics/3', 'ToWksp_acc/1', 'autorouting', 'on');
add_line(model_name, 'MR_Damper_Bouc_Wen/1', 'ToWksp_force/1', 'autorouting', 'on');

%% Beautify Layout & Colors
set_param(road_sub, 'BackgroundColor', 'LightBlue');
set_param(ctrl_sub, 'BackgroundColor', 'PaleGreen');
set_param(mrd_sub, 'BackgroundColor', 'Orange');
set_param(qc_sub, 'BackgroundColor', 'Yellow');

% Save model
save_system(model_name);
fprintf('Simulink model [%s.slx] built and saved successfully!\n', model_name);
